"""Generate narrative-ready summaries from forecast outputs."""

from __future__ import annotations

import argparse
import logging
from pathlib import Path

import pandas as pd
from utils.storytelling import build_narrative_brief

logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create narrative briefs from forecast outputs"
    )
    parser.add_argument(
        "--forecasts",
        type=Path,
        default=Path(__file__).resolve().parents[1]
        / "reports"
        / "forecast_outputs.parquet",
        help="Forecast outputs generated by run_forecasts.py",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "reports" / "narrative_briefs.md",
        help="Markdown file summarizing key narrative angles",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    df = pd.read_parquet(args.forecasts)
    brief = build_narrative_brief(df)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(brief, encoding="utf-8")
    logger.info(f"✓ Narrative brief saved -> {args.output}")


if __name__ == "__main__":
    main()
